# view_report.py
import os
import webbrowser

# Create HTML content
html_content = """<!DOCTYPE html>
<html>
<head>
    <title>Weather Analysis Results</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 0;
            padding: 20px; 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        h1 { 
            color: white; 
            text-align: center;
            font-size: 2.5em;
            margin-bottom: 30px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }
        .container { 
            max-width: 1400px; 
            margin: 0 auto; 
        }
        .stats { 
            background: rgba(255,255,255,0.95); 
            padding: 25px; 
            border-radius: 15px; 
            margin: 20px 0 30px 0; 
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }
        .stats h2 {
            color: #333;
            margin-top: 0;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .image-grid { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); 
            gap: 25px; 
        }
        .image-card { 
            background: white; 
            padding: 20px; 
            border-radius: 15px; 
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
            transition: transform 0.3s ease;
        }
        .image-card:hover {
            transform: translateY(-5px);
        }
        .image-card img { 
            width: 100%; 
            height: auto; 
            border-radius: 10px; 
            border: 3px solid #f0f0f0;
        }
        .image-card h3 { 
            margin: 0 0 15px 0; 
            color: #333;
            font-size: 1.2em;
            text-align: center;
        }
        .footer { 
            text-align: center; 
            margin-top: 40px; 
            color: white;
            padding: 20px;
        }
        .badge {
            background: #667eea;
            color: white;
            padding: 5px 10px;
            border-radius: 5px;
            font-size: 0.9em;
            display: inline-block;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🌍 Global Weather Analysis Results</h1>
        
        <div class="stats">
            <h2>📊 Analysis Complete!</h2>
            <p>The following visualizations have been generated from the Global Weather dataset. 
            Click on any image to view in full size.</p>
            <div class="badge">PM Accelerator Mission: AI-Driven Solutions</div>
        </div>
        
        <div class="image-grid">
"""

# Get the absolute path for images
figures_dir = "outputs/figures"
if os.path.exists(figures_dir):
    # Sort files to display in order
    image_files = sorted([f for f in os.listdir(figures_dir) if f.endswith('.png')])
    
    for filename in image_files:
        # Create a nice title from filename
        title = filename.replace('_', ' ').replace('.png', '').title()
        
        html_content += f"""
            <div class="image-card">
                <h3>{title}</h3>
                <img src="figures/{filename}" alt="{filename}" onclick="window.open(this.src)">
            </div>
        """

html_content += """
        </div>
        
        <div class="footer">
            <p>Generated by Weather Forecasting Project | 
            <a href="#" style="color: white;">Back to Top</a></p>
        </div>
    </div>
</body>
</html>
"""

# Save the HTML file
with open('outputs/gallery.html', 'w', encoding='utf-8') as f:
    f.write(html_content)

print("="*60)
print("✅ Gallery created successfully!")
print(f"📁 Location: {os.path.abspath('outputs/gallery.html')}")
print("="*60)

# Open the file in browser
html_path = os.path.abspath('outputs/gallery.html')
webbrowser.open('file://' + html_path)
print(f"🌐 Opening gallery in your browser...")